language: node_js
node_js: "node"
sudo: true
before_script:
    - cd realtime; npm install; cd ..
    - cd client; npm install; bower install; cd ..
script: 
    - cd realtime && npm test && cd ..
    - cd client && npm test && cd ..
    - cd client && find . -regex ".*\.jsx?"|grep -v node_modules/|grep -v bower_components/|grep -v dist/|xargs eslint && cd ..
    - cd API && sudo pip install --no-cache-dir -r requirements.txt && python manage.py test chat && cd ..
