# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20180311_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinguser',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
